### ISSUE TITLE
Possible annotation errors for human-written captions

### ISSUE THREAD

**Issue by HAWLYQ** [jungokasai/THumB#1]
Hi, Jungo. 
Thanks for your contribution to caption evaluation. When using mscoco_THUmb-1.0.jsonl, we find there are some annotation errors for human-written captions. For example, the caption is totally irrelevant with the image but given high scores. We make a list of possible wrong annotations, please have a check. 

[possible_wrong_anno_by_haw.txt](https://github.com/jungokasai/THumB/files/7837036/possible_wrong_anno_by_haw.txt)

**Comment by jungokasai** [comment]
Thank you so much for catching this. Indeed, I misaligned some of the outputs from Human. I fixed the problem: https://github.com/jungokasai/THumB/commit/35e97e11bf9b9b853ed8cc81d75215f5b8205d95. 
I believe there is no problem with the human evaluations per se. 

Tables 2 and 4 of the paper should also be corrected accordingly since I used these misaligned data:

<img width="763" alt="Screen Shot 2022-01-12 at 2 27 58 PM" src="https://user-images.githubusercontent.com/12591401/149233452-076e7d7e-e00e-4ee3-81f9-107b33adf10e.png">
<img width="364" alt="Screen Shot 2022-01-12 at 2 31 38 PM" src="https://user-images.githubusercontent.com/12591401/149233509-c3ac9d95-abc3-4b17-9633-a007297d4e4d.png">


General patterns discussed in the paper still persist, but overall we see better correlations in the w/ Human setting. They were lower because automatic metrics were computed based on the partially misaligned example indices.
